# Railway.app configuration file for frontend
[build]
  builder = "NIXPACKS"
  buildCommand = "npm ci && npm run build"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/"
  healthcheckTimeout = 60
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

[env]
  NODE_ENV = "production"